### ISSUE TITLE
Error jinja2.exceptions.TemplateNotFound

### ISSUE THREAD

**Issue by koddr** [mhausenblas/mkdocs-deploy-gh-pages#23]
Hi 👋 

I faced with strange error with your Action, when I try to deploy my [repo](https://github.com/create-go-app/website).

GH Pages settings:

![Screenshot 2020-07-03 at 18 21 57](https://user-images.githubusercontent.com/11155743/86482180-1bd6f500-bd5a-11ea-9e82-25f1d370783c.png)

Link to `mkdocs.yml`: https://github.com/create-go-app/website/blob/master/mkdocs.yml

Logs from GH Actions:

```
2020-07-03T15:17:42.4110297Z INFO    -  Cleaning site directory 
2020-07-03T15:17:42.4110936Z INFO    -  Building documentation to directory: /github/workspace/site 
2020-07-03T15:17:42.9666744Z Traceback (most recent call last):
2020-07-03T15:17:42.9666992Z   File "/usr/local/bin/mkdocs", line 8, in <module>
2020-07-03T15:17:42.9667158Z     sys.exit(cli())
2020-07-03T15:17:42.9668001Z   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 829, in __call__
2020-07-03T15:17:42.9668205Z     return self.main(*args, **kwargs)
2020-07-03T15:17:42.9668609Z   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 782, in main
2020-07-03T15:17:42.9668782Z     rv = self.invoke(ctx)
2020-07-03T15:17:42.9669162Z   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
2020-07-03T15:17:42.9669348Z     return _process_result(sub_ctx.command.invoke(sub_ctx))
2020-07-03T15:17:42.9669749Z   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
2020-07-03T15:17:42.9669928Z     return ctx.invoke(self.callback, **ctx.params)
2020-07-03T15:17:42.9670325Z   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
2020-07-03T15:17:42.9670501Z     return callback(*args, **kwargs)
2020-07-03T15:17:42.9670927Z   File "/usr/local/lib/python3.8/site-packages/mkdocs/__main__.py", line 183, in gh_deploy_command
2020-07-03T15:17:42.9671106Z     build.build(cfg, dirty=not clean)
2020-07-03T15:17:42.9671505Z   File "/usr/local/lib/python3.8/site-packages/mkdocs/commands/build.py", line 288, in build
2020-07-03T15:17:42.9671696Z     _build_theme_template(template, env, files, config, nav)
2020-07-03T15:17:42.9672140Z   File "/usr/local/lib/python3.8/site-packages/mkdocs/commands/build.py", line 114, in _build_theme_template
2020-07-03T15:17:42.9672345Z     output = _build_template(template_name, template, files, config, nav)
2020-07-03T15:17:42.9672790Z   File "/usr/local/lib/python3.8/site-packages/mkdocs/commands/build.py", line 93, in _build_template
2020-07-03T15:17:42.9672967Z     output = template.render(context)
2020-07-03T15:17:42.9673371Z   File "/usr/local/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
2020-07-03T15:17:42.9673549Z     self.environment.handle_exception()
2020-07-03T15:17:42.9674196Z   File "/usr/local/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
2020-07-03T15:17:42.9674393Z     reraise(*rewrite_traceback_stack(source=source))
2020-07-03T15:17:42.9674919Z   File "/usr/local/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
2020-07-03T15:17:42.9675077Z     raise value.with_traceback(tb)
2020-07-03T15:17:42.9675497Z   File "/usr/local/lib/python3.8/site-packages/material/404.html", line 4, in top-level template code
2020-07-03T15:17:42.9675678Z     {% extends "base.html" %}
2020-07-03T15:17:42.9676100Z   File "/usr/local/lib/python3.8/site-packages/material/base.html", line 176, in top-level template code
2020-07-03T15:17:42.9676275Z     {% block footer %}
2020-07-03T15:17:42.9676682Z   File "/usr/local/lib/python3.8/site-packages/material/base.html", line 177, in block "footer"
2020-07-03T15:17:42.9676860Z     {% include "partials/footer.html" %}
2020-07-03T15:17:42.9677308Z   File "/usr/local/lib/python3.8/site-packages/material/partials/footer.html", line 55, in top-level template code
2020-07-03T15:17:42.9677487Z     {% include "partials/social.html" %}
2020-07-03T15:17:42.9677910Z   File "/usr/local/lib/python3.8/site-packages/material/partials/social.html", line 10, in top-level template code
2020-07-03T15:17:42.9678097Z     {% include ".icons/" ~ social.icon ~ ".svg" %}
2020-07-03T15:17:42.9678503Z   File "/usr/local/lib/python3.8/site-packages/jinja2/loaders.py", line 199, in get_source
2020-07-03T15:17:42.9678678Z     raise TemplateNotFound(template)
2020-07-03T15:17:42.9679051Z jinja2.exceptions.TemplateNotFound: .icons/octicons/octoface-16.svg
```

How to solve it? Please help me 😢

**Comment by mhausenblas** [comment]
Can you try and remove [lines 89 and 90](https://github.com/create-go-app/website/blob/master/mkdocs.yml#L89-L90)  in your `mkdocs.yml` and see if that works?

**Comment by koddr** [comment]
@mhausenblas yep, gotcha! It's because in your Action not installed some extensions (`pymdown-extensions`). I switched to plain `run` and it works fine: https://github.com/create-go-app/website/blob/master/.github/workflows/deploy_gh-pages.yml#L22-L40

> Btw, why do you even need this kind of action, when you can do the same with common `run`? Hmm... 🤔
