### ISSUE TITLE
Command '['git', 'push', 'origin', 'gh-pages', '--force']' returned non-zero exit status 1

### ISSUE THREAD

**Issue by saket** [mhausenblas/mkdocs-deploy-gh-pages#246]
Hello. I'm not sure why, but `mkdocs-deploy-gh-pages` is failing for my repository. Is there any way I can investigate what might be happening?

Could my repository's private visibility be causing this? FWIW running `mkdocs gh-deploy` manually from my local machine is working fine.

```
error: failed to push some refs to 'https://github.com/saket/telephoto.git'
Traceback (most recent call last):
  File "/usr/local/bin/mkdocs", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/mkdocs/__main__.py", line 280, in gh_deploy_command
    gh_deploy.gh_deploy(
  File "/usr/local/lib/python3.11/site-packages/mkdocs/commands/gh_deploy.py", line 1[27](https://github.com/saket/telephoto/actions/runs/4827005497/jobs/8599397999#step:4:28), in gh_deploy
    ghp_import.ghp_import(
  File "/usr/local/lib/python3.11/site-packages/ghp_import.py", line [28](https://github.com/saket/telephoto/actions/runs/4827005497/jobs/8599397999#step:4:29)3, in ghp_import
    git.check_call('push', opts['remote'], opts['branch'], '--force')
  File "/usr/local/lib/python3.11/site-packages/ghp_import.py", line 119, in check_call
    sp.check_call(['git'] + list(args), **kwargs)
  File "/usr/local/lib/python3.11/subprocess.py", line [41](https://github.com/saket/telephoto/actions/runs/4827005497/jobs/8599397999#step:4:42)3, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['git', 'push', 'origin', 'gh-pages', '--force']' returned non-zero exit status 1.
##[debug]Docker Action run completed with exit code 1
##[debug]Finishing: Deploy docs
```

Here's my action file:

```yml
name: Publish project website

on:
  push:
    branches: [ trunk ]

jobs:
  deploy-website:
    name: Deploy mkdocs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@1.26
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CONFIG_FILE: mkdocs.yml
          REQUIREMENTS: .github/workflows/mkdocs_requirements.txt
```

**Comment by saket** [comment]
Turns out I was missing an `EXTRA_PACKAGES: git-lfs` line (https://github.com/saket/telephoto/commit/4a320ec1adaf03f049927d2bfeed2d2e7d5c5f75)
